Repository depromeet/bread-map-front, pull requests merged in 2021-12, with the labels that each got.

#128 [#127] 삭제된 코드 revert
  web/src/components/AddBreadReview/CategorySelect.tsx
  web/src/components/AddBreadReview/MainAdd.tsx
  web/src/components/AddBreadReview/MoreAdd.tsx
  web/src/components/AddBreadReview/ReviewTab.tsx
  web/src/components/AddBreadReview/StartAdd.tsx
  web/src/components/AddBreadReview/index.tsx
  web/src/components/common/index.ts
  web/src/components/signin/GoogleSignInButton.tsx
  web/src/pages/addBread.tsx
Labels: 🔨 리팩토링

#129 [#126] 기능: 빵집 등록 api 연결
  web/src/components/addBakery/AddBakeryAddress.tsx
  web/src/components/addBakery/AddBakeryInfo.tsx
  web/src/components/addBakery/AddBakeryInput/AddBakeryCardInput.tsx
  web/src/components/addBakery/AddBakeryInput/AddBakeryInput.tsx
  web/src/components/addBakery/AddBakeryInput/AddBakeryMultiInput.tsx
  web/src/components/addBakery/AddBakeryInput/AddBakeryTextArea.tsx
  web/src/components/addBakery/AddBakeryInput/index.ts
  web/src/components/addBakery/AddBakeryOnBoard.tsx
  web/src/components/addBakery/index.tsx
  web/src/components/addStore/StoreInput/index.ts
  web/src/components/addStore/index.tsx
  web/src/components/bakery/TabContents/InfoSection/BakeryCategories.tsx
  web/src/components/bakery/TabContents/InfoSection/index.tsx
  web/src/components/common/BakeryBaseCategoryList/Categories.tsx
  web/src/components/common/BakeryBaseCategoryList/index.tsx
  web/src/components/common/BakeryBaseCategoryList/useCategories.ts
  web/src/components/common/Footer.tsx
  web/src/components/common/StoreBaseCategoryList/index.tsx
  web/src/components/map/BakeryCardList.tsx
  web/src/constants/bakeryBaseCategories.ts
  web/src/pages/add-bakery.tsx
  web/src/remotes/hooks/useGeocode.ts
  web/src/remotes/network/bakery/requestCreateBakery.ts
  web/src/remotes/network/bakery/requestGeocode.ts
  web/src/store/addBakeryAddress.ts
  web/src/store/index.ts
Labels: 💡 기능

#140 [#133] qa: 현재 위치 표시 추가
  web/src/components/map/BakeryMap.tsx
  web/src/lib/navermap/index.ts
  web/src/lib/navermap/useDrawCurrentPosition.ts
Labels: 💡 기능, QA

#130 [#105] 기능 : 프로필 가보고 싶어요 탭 구현
  web/src/components/UserProfile/MainProfile.tsx
  web/src/components/UserProfile/TabContents/ReviewSection/index.tsx
  web/src/components/UserProfile/TabContents/WentSection/index.tsx
  web/src/components/UserProfile/TabContents/WishSection/index.tsx
  web/src/components/UserProfile/TabContents/index.tsx
Labels: 💡 기능

#144 [#143] 버그: 빵 등록 페이지 복구후 버그 수정
  web/src/components/AddBreadReview/CategorySelect.tsx
  web/src/components/AddBreadReview/MainAdd.tsx
  web/src/components/AddBreadReview/MoreAdd.tsx
  web/src/components/AddBreadReview/StartAdd.tsx
  web/src/components/AddBreadReview/index.tsx
  web/src/components/common/BreadCategoryList/Categories.tsx
Labels: ⛔ 버그

#151 [#150] 프로필 페이지 가보고 싶어요 탭 리스트 출력
  web/.gitignore
  web/src/components/UserProfile/TabContents/WishSection/index.tsx
  web/src/components/map/BakeryInfoCard.tsx
  web/src/remotes/hooks/index.ts
  web/src/remotes/hooks/useGetUserFlagBakeries.ts
  web/src/remotes/network/bakery/requestModifyBakeryFlag.ts
  web/src/remotes/network/member/index.ts
  web/src/remotes/network/member/requestGetUserFlagBakeries.ts
Labels: 💡 기능

#159 [#147] qa: ios category 스크롤 버그
  web/src/components/common/CategoryList.tsx
Labels: ⛔ 버그, QA

#161 [#160] qa: center position icon modified
  web/src/lib/navermap/useDrawCurrentPosition.ts
Labels: 🎨 디자인, QA

#152 [#149] 기능: addBread api 연결
  web/src/components/AddBreadReview/MainAdd.tsx
  web/src/components/AddBreadReview/MoreAdd.tsx
  web/src/components/AddBreadReview/StartAdd.tsx
  web/src/components/AddBreadReview/index.tsx
  web/src/remotes/hooks/index.ts
  web/src/remotes/hooks/useCreateBakeryMenuReview.ts
  web/src/remotes/network/bakery/requestCreateBakeryMenuReview.ts
Labels: 💡 기능

#163 기능: 빵 카테고리 필터 초기화 버튼
  web/src/components/map/BreadFilterSelect.tsx
Labels: 💡 기능, QA

#165 기능: 빵집등록 커버 autoplay
  web/.pnp.cjs
  web/.yarn/cache/keen-slider-npm-5.5.1-58840bdf2b-4788384577.zip
  web/.yarn/cache/keen-slider-npm-6.4.0-15011fc9b4-2f4f688ab3.zip
  web/package.json
  web/src/components/addBakery/AddBakeryOnBoard.tsx
  web/yarn.lock
Labels: 💡 기능, QA

#170 버그: app 빌드오류 수정
  web/src/components/AddBreadReview/index.tsx
Labels: ⛔ 버그

#174 기능: 빵집 리뷰등록 완성
  web/src/components/AddBreadReview/AddBreadReviewInput/CategoryInput.tsx
  web/src/components/AddBreadReview/AddBreadReviewInput/PhotoInput.tsx
  web/src/components/AddBreadReview/AddBreadReviewInput/ReviewTextInput.tsx
  web/src/components/AddBreadReview/AddBreadReviewInput/ScoreInput.tsx
  web/src/components/AddBreadReview/AddBreadReviewInput/index.ts
  web/src/components/AddBreadReview/CategorySelect.tsx
  web/src/components/AddBreadReview/EditReview.tsx
  web/src/components/AddBreadReview/MainAdd.tsx
  web/src/components/AddBreadReview/MoreAdd.tsx
  web/src/components/AddBreadReview/ResultModal.tsx
  web/src/components/AddBreadReview/ReviewTab.tsx
  web/src/components/AddBreadReview/StartAdd.tsx
  web/src/components/AddBreadReview/index.tsx
  web/src/components/addBakery/AddBakeryInfo.tsx
  web/src/components/addBread/AddBreadHeader.tsx
  web/src/components/addBread/BreadCategoryList.tsx
  web/src/components/addBread/BreadCategorySelect.tsx
  web/src/components/addBread/ReviewForm.tsx
  web/src/components/addBread/ReviewTabs.tsx
  web/src/components/addBread/StartTitle.tsx
  web/src/components/addBread/index.ts
  web/src/components/bakery/TabContents/HomeSection/index.tsx
  web/src/components/bakery/TabContents/MenuSection/index.tsx
  web/src/components/bakery/TabContents/ReviewSection/index.tsx
  web/src/components/common/BakeryBaseCategoryList/Categories.tsx
  web/src/components/common/BreadCategoryList/Categories.tsx
  web/src/components/common/Images/index.tsx
  web/src/components/common/ToastPopup/Toast.tsx
  web/src/components/icons/OkSobbang.tsx
  web/src/components/icons/index.ts
  web/src/pages/add-bread.tsx
  web/src/pages/add-bread/[id].tsx
  web/src/pages/addBread.tsx
  web/src/pages/star.tsx
  web/src/remotes/network/bakery/requestCreateBakeryMenuReview.ts
Labels: 💡 기능

#178 [#176] 버그: image url에 public s3 url이 중복되는 문제
  web/public/.well-known/assetlinks.json
  web/src/components/UserProfile/TabContents/WishSection/index.tsx
  web/src/components/map/BakeryCardList.tsx
Labels: ⛔ 버그, QA

#179 [#177] QA: 리뷰등록
  web/src/components/AddBreadReview/MainAdd.tsx
  web/src/components/AddBreadReview/ResultModal.tsx
  web/src/components/AddBreadReview/ReviewDeleteModal.tsx
  web/src/components/AddBreadReview/ReviewMaxLengthModal.tsx
  web/src/components/icons/SadSobbang.tsx
  web/src/components/icons/index.ts
Labels: 💡 기능, QA

#180 [#148] QA: 아이폰 상세페이지 탭 하단 border 크기
  web/src/components/bakery/StoreDetailTabs.tsx
Labels: 🎨 디자인, QA

#182 [#181] 기능 : footer 미동작 페이지 임시제거
  web/src/components/common/Footer.tsx
Labels: 💡 기능

#175 [#169] 기능 : url 드롭다운 기능 구현
  web/src/components/bakery/TabContents/InfoSection/BlueLink.tsx
  web/src/components/bakery/TabContents/InfoSection/WebSiteList.tsx
  web/src/components/bakery/TabContents/InfoSection/index.tsx
  web/src/components/icons/TouchAreaDownIcon.test.tsx
  web/src/components/icons/TouchAreaDownIcon.tsx
  web/src/components/icons/TouchAreaUpIcon.tsx
  web/src/components/icons/TounchAreaUpIcon.test.tsx
  web/src/components/icons/index.ts
Labels: 💡 기능
