Repository depromeet/bread-map-front, pull requests merged in 2021-11, with the labels that each got.

#88 [#86] 빵등록 페이지 추가기능 구현
  web/src/components/AddBreadReview/MainAdd.tsx
  web/src/components/AddBreadReview/MoreAdd.test.tsx
  web/src/components/AddBreadReview/MoreAdd.tsx
  web/src/components/AddBreadReview/StartAdd.test.tsx
  web/src/components/AddBreadReview/StartAdd.tsx
  web/src/components/common/ToastPopup/Toast.tsx
  web/src/components/common/ToastPopup/index.tsx
  web/src/components/common/ToastPopup/useToast.ts
Labels: ⛔ 버그, 💡 기능, 🎨 디자인

#90 [#76] 기능: 빵집 등록하기 온보딩 페이지 구현
  web/.pnp.cjs
  web/.yarn/cache/keen-slider-npm-5.5.1-58840bdf2b-4788384577.zip
  web/package.json
  web/public/images/onboarding_01.png
  web/public/images/onboarding_02.png
  web/public/images/onboarding_03.png
  web/public/images/onboarding_04.png
  web/public/images/onboarding_05.png
  web/src/components/common/Button.tsx
  web/src/pages/_document.tsx
  web/src/pages/onboard.tsx
  web/yarn.lock
Labels: 💡 기능

#89 [#75] 탐색 페이지 (공사중) 구현
  web/src/components/icons/Construction.tsx
  web/src/components/icons/index.ts
  web/src/pages/search.tsx
Labels: 💡 기능, 🎨 디자인

#97 [#83] 기능: swagger api 연결
  web/src/remotes/hooks/useGetBakeries.ts
  web/src/remotes/network/auth/index.ts
  web/src/remotes/network/auth/requestRefreshLogin.ts
  web/src/remotes/network/auth/requestSocialLogin.ts
  web/src/remotes/network/auth/types.ts
  web/src/remotes/network/bakeries.ts
  web/src/remotes/network/bakery/index.ts
  web/src/remotes/network/bakery/requestCreateBakery.ts
  web/src/remotes/network/bakery/requestCreateBakeryMenuReview.ts
  web/src/remotes/network/bakery/requestDeleteBakeryMenuReview.ts
  web/src/remotes/network/bakery/requestGetBakeries.ts
  web/src/remotes/network/bakery/requestGetBakery.ts
  web/src/remotes/network/bakery/requestGetBakeryMenu.ts
  web/src/remotes/network/bakery/requestGetBakeryMenuReview.ts
  web/src/remotes/network/bakery/requestGetCategoryMenu.ts
  web/src/remotes/network/bakery/requestModifyBakeryFlag.ts
  web/src/remotes/network/bakery/requestModifyBakeryRating.ts
  web/src/remotes/network/fetchBase.ts
  web/src/remotes/network/image/index.ts
  web/src/remotes/network/image/requestDeleteImage.ts
  web/src/remotes/network/image/requestUploadImage.ts
Labels: 💡 기능

#96 [#85] 로그인 페이지 UI 마크업
  web/public/images/signin.png
  web/src/components/signin/GoogleSignInButton.tsx
  web/src/components/signin/KakaoSignInButton.tsx
  web/src/components/signin/SignInTitle.tsx
  web/src/components/signin/index.ts
  web/src/pages/auth/signin.tsx
Labels: 💡 기능

#93 [#82] 기능 : 카테고리 디자인 수정 및 바텀시트가 카테고리 가리는 오류 수정
  web/.pnp.cjs
  web/.yarn/cache/@testing-library-react-hooks-npm-7.0.2-da146b13d2-27c6169b5c.zip
  web/.yarn/cache/@types-react-dom-npm-17.0.11-fc2e584a96-4d5730dffb.zip
  web/.yarn/cache/@types-react-npm-17.0.34-7a53209557-16729ad7d5.zip
  web/.yarn/cache/@types-react-test-renderer-npm-17.0.1-9a42d8bb68-ecaae8df36.zip
  web/.yarn/cache/react-error-boundary-npm-3.1.4-2310dba89e-f36270a5d7.zip
  web/package.json
  web/src/components/common/CategoryList/useCategories.ts
  web/src/components/daedong/CategorySide.tsx
  web/src/components/daedong/DaedongBottomSheet.tsx
  web/src/components/daedong/DaedongMap/CategoryButton.tsx
  web/src/components/daedong/DaedongMap/CurrentPositionButton.tsx
  web/src/components/daedong/DaedongMap/MapButton.test.tsx
  web/src/components/daedong/DaedongMap/MapButton.tsx
  web/src/components/daedong/DaedongMap/SideButtons.test.tsx
  web/src/components/daedong/DaedongMap/SideButtons.tsx
  web/src/components/daedong/DaedongMap/index.tsx
  web/src/components/daedong/SideButtons.test.tsx
  web/src/components/daedong/SideButtons.tsx
  web/src/components/daedong/index.ts
  web/src/components/icons/Bread.tsx
  web/src/components/icons/Close.tsx
  web/src/pages/daedong.tsx
  web/src/store/breadMapCategorySlide.ts
  web/src/store/breadMapSelectedCategotyItem.ts
  web/src/store/index.ts
  web/yarn.lock
Labels: ⛔ 버그, 💡 기능, 🎨 디자인, ⚙ 설정

#91 [#74] 프로필 페이지 기본 틀 구현
  web/src/components/UserProfile/EditProfile.test.tsx
  web/src/components/UserProfile/EditProfile.tsx
  web/src/components/UserProfile/MainProfile.test.tsx
  web/src/components/UserProfile/MainProfile.tsx
  web/src/components/UserProfile/Settings.test.tsx
  web/src/components/UserProfile/Settings.tsx
  web/src/components/UserProfile/index.tsx
  web/src/pages/profile.tsx
Labels: 🎨 디자인

#99 [#63] 기능: 빵집 등록하기 페이지 구현
  web/public/images/thumbnail.png
  web/src/components/AddBreadReview/CategorySelect.tsx
  web/src/components/AddBreadReview/MainAdd.tsx
  web/src/components/addStore/StoreAddress.tsx
  web/src/components/addStore/StoreInfo.tsx
  web/src/components/addStore/StoreInput/StoreCardInput.tsx
  web/src/components/addStore/StoreInput/StoreInput.tsx
  web/src/components/addStore/StoreInput/StoreMultiInput.tsx
  web/src/components/addStore/StoreInput/index.ts
  web/src/components/addStore/StoreOnBoard.tsx
  web/src/components/addStore/index.tsx
  web/src/components/common/BreadCategoryList/Categories.tsx
  web/src/components/common/BreadCategoryList/index.tsx
  web/src/components/common/BreadCategoryList/useCategories.ts
  web/src/components/common/Button.tsx
  web/src/components/common/Header.tsx
  web/src/components/common/StoreBaseCategoryList/Categories.tsx
  web/src/components/common/StoreBaseCategoryList/index.tsx
  web/src/components/common/StoreBaseCategoryList/useCategories.ts
  web/src/components/common/index.ts
  web/src/components/icons/ArrowPrev.tsx
  web/src/components/icons/Close.tsx
  web/src/components/icons/InfoWifiIcon.tsx
  web/src/components/icons/Plus.tsx
  web/src/components/postcode/Postcode.tsx
  web/src/constants/breadCategories.ts
  web/src/constants/storeBaseCategories.ts
  web/src/pages/addBread.tsx
  web/src/pages/addStore.tsx
  web/src/store/addStoreAddress.ts
  web/src/store/index.ts
Labels: 💡 기능, 🔄 진행중

#101 [#100] 기능 : confirm용 바텀 모달 추가
  web/src/components/addStore/StoreAddress.tsx
  web/src/components/addStore/StoreInput/StoreMultiInput.tsx
  web/src/components/common/ConfirmModal.tsx
  web/src/components/common/StoreBaseCategoryList/Categories.tsx
  web/src/components/common/index.ts
  web/src/components/daedong/CategorySide.tsx
Labels: ⛔ 버그, 💡 기능

#106 [#98] 기능: 메인페이지 코드 병합 & 리팩토링
  web/src/components/AddBreadReview/CategorySelect.tsx
  web/src/components/AddBreadReview/MainAdd.tsx
  web/src/components/AddBreadReview/MoreAdd.tsx
  web/src/components/AddBreadReview/StartAdd.tsx
  web/src/components/AddBreadReview/index.tsx
  web/src/components/addBread/AddBreadHeader.tsx
  web/src/components/addBread/BreadCategoryList.tsx
  web/src/components/addBread/BreadCategorySelect.tsx
  web/src/components/addBread/ReviewForm.tsx
  web/src/components/addBread/ReviewTabs.tsx
  web/src/components/addBread/StartTitle.tsx
  web/src/components/addBread/index.ts
  web/src/components/common/CategoryList.tsx
  web/src/components/common/Footer.tsx
  web/src/components/common/index.ts
  web/src/components/daedongMap/BreadFilterButton.tsx
  web/src/components/daedongMap/CategoryList.tsx
  web/src/components/daedongMap/types.ts
  web/src/components/map/BakeryCardList.tsx
  web/src/components/map/BakeryInfoCard.tsx
  web/src/components/map/BakeryMap.tsx
  web/src/components/map/BakeryMarkers.tsx
  web/src/components/map/BreadFilterButton.tsx
  web/src/components/map/BreadFilterSelect.tsx
  web/src/components/map/CurrentPositionButton.tsx
  web/src/components/map/DaedongMapContainer.tsx
  web/src/components/map/FlagFilterButton.tsx
  web/src/components/map/constants.ts
  web/src/components/map/index.ts
  web/src/constants/breadCategories.ts
  web/src/pages/add-bread.tsx
  web/src/pages/daedong/map.tsx
  web/src/pages/map.tsx
  web/src/remotes/hooks/useGetBakeries.ts
  web/src/remotes/network/auth/requestSocialLogin.ts
  web/src/remotes/network/bakeries.ts
  web/src/remotes/network/bakery/requestCreateBakery.ts
  web/src/remotes/network/bakery/requestDeleteBakeryMenuReview.ts
  web/src/remotes/network/bakery/requestGetBakeries.ts
  web/src/remotes/network/bakery/requestGetBakeryMenuReview.ts
  web/src/remotes/network/bakery/requestModifyBakeryFlag.ts
  web/src/remotes/network/bakery/requestModifyBakeryRating.ts
  web/src/remotes/network/image/requestDeleteImage.ts
  web/src/store/addBread.ts
  web/src/store/map.ts
Labels: 💡 기능, 🔨 리팩토링, 🔄 진행중

#109 [#108] 스타일: dev branch prettier
  web/src/components/addBread/AddBreadHeader.tsx
  web/src/components/addBread/BreadCategoryList.tsx
  web/src/components/addBread/BreadCategorySelect.tsx
  web/src/components/addBread/ReviewForm.tsx
  web/src/components/addBread/ReviewTabs.tsx
  web/src/components/addBread/StartTitle.tsx
  web/src/components/addStore/StoreInput/StoreMultiInput.tsx
  web/src/components/common/CategoryList.tsx
  web/src/components/map/BakeryCardList.tsx
  web/src/components/map/BakeryMap.tsx
  web/src/components/map/BakeryMarkers.tsx
  web/src/components/map/BreadFilterButton.tsx
  web/src/components/map/BreadFilterSelect.tsx
  web/src/components/map/CurrentPositionButton.tsx
  web/src/components/map/DaedongMapContainer.tsx
  web/src/components/postcode/Postcode.tsx
  web/src/constants/breadCategories.ts
  web/src/lib/navermap/NaverMap.tsx
  web/src/pages/add-bread.tsx
  web/src/pages/addBread.tsx
  web/src/pages/map.tsx
  web/src/remotes/network/bakery/requestDeleteBakeryMenuReview.ts
  web/src/remotes/network/bakery/requestGetBakeryMenuReview.ts
  web/src/store/addBread.ts
  web/src/store/map.ts
Labels: ⌨ 스타일

#111 [#100] 기능: 빵집 상세페이지 full screen 용 추가
  web/public/images/default_bread.png
  web/public/images/mock_bread_img_1.png
  web/public/images/mock_bread_img_2.png
  web/public/images/mock_bread_img_3.png
  web/public/images/noProfileImg.png
  web/public/images/sadSobbang.png
  web/src/components/breadStore/BakeryHeader.tsx
  web/src/components/breadStore/StoreDetailTabs.tsx
  web/src/components/breadStore/TabContents/HomeSection/MenuCardList.tsx
  web/src/components/breadStore/TabContents/HomeSection/ReviewCardList.tsx
  web/src/components/breadStore/TabContents/HomeSection/StoreRating.tsx
  web/src/components/breadStore/TabContents/HomeSection/index.tsx
  web/src/components/breadStore/TabContents/InfoSection/BakeryCategories.tsx
  web/src/components/breadStore/TabContents/InfoSection/index.tsx
  web/src/components/breadStore/TabContents/MenuSection/MenuCardList.tsx
  web/src/components/breadStore/TabContents/MenuSection/index.tsx
  web/src/components/breadStore/TabContents/ReviewSection/ReviewCardList.tsx
  web/src/components/breadStore/TabContents/ReviewSection/StoreRating.tsx
  web/src/components/breadStore/TabContents/ReviewSection/index.tsx
  web/src/components/breadStore/TabContents/index.tsx
  web/src/components/breadStore/index.ts
  web/src/components/common/BreadCategoryList/Categories.tsx
  web/src/components/common/Button.tsx
  web/src/components/common/Header.tsx
  web/src/components/common/StoreBaseCategoryList/Categories.tsx
  web/src/components/common/StoreBaseCategoryList/useCategories.ts
  web/src/components/icons/EarthIcon.tsx
  web/src/components/icons/FileTextIcon.tsx
  web/src/components/icons/UserCircle.tsx
  web/src/components/icons/index.ts
  web/src/constants/storeBaseCategories.ts
  web/src/mocks/data/bakery.ts
  web/src/mocks/data/bakeryMenu.ts
  web/src/mocks/data/bakeryReview.ts
  web/src/mocks/data/index.ts
  web/src/mocks/data/mapBakery.ts
  web/src/mocks/handlers.ts
  web/src/pages/bread-store/[id].tsx
  web/src/remotes/hooks/index.ts
  web/src/remotes/hooks/useGetBakery.tsx
  web/src/remotes/hooks/useGetBakeryMenu.tsx
  web/src/remotes/hooks/useGetBakeryMenuReivew.tsx
  web/src/remotes/network/bakery/requestGetBakery.ts
  web/src/store/breadMapSelectedCategotyItem.ts
  web/src/store/breadStoreName.ts
  web/src/store/index.ts
Labels: 💡 기능

#110 [#104] 기능: 별점 슬라이드 기능 구현
  web/src/components/common/StarScore/index.tsx
  web/src/components/common/StarScore/useMountedState.ts
  web/src/components/common/StarScore/useSetState.ts
  web/src/components/common/StarScore/useSlider.ts
  web/src/pages/star.tsx
  web/src/utils/slideUtils.ts
Labels: 💡 기능
