Repository depromeet/bread-map-front, pull requests merged in 2021-09, with the labels that each got.

#2 [#1] 설정 : 이슈, PR 템플릿, 자동 Assignees 추가
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
Labels: ⚙️ 설정

#6 설정: 안드로이드 Jetpack compose 웹뷰 기본 설정
  android/.gitignore
  android/.idea/.name
  android/.idea/codeStyles/Project.xml
  android/.idea/codeStyles/codeStyleConfig.xml
  android/.idea/compiler.xml
  android/.idea/gradle.xml
  android/.idea/misc.xml
  android/.idea/vcs.xml
  android/app/.gitignore
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/example/breadmap/ExampleInstrumentedTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/breadmap/MainActivity.kt
  android/app/src/main/java/com/example/breadmap/ui/theme/Color.kt
  android/app/src/main/java/com/example/breadmap/ui/theme/Shape.kt
  android/app/src/main/java/com/example/breadmap/ui/theme/Theme.kt
  android/app/src/main/java/com/example/breadmap/ui/theme/Type.kt
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/test/java/com/example/breadmap/ExampleUnitTest.kt
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
Labels: ⚙ 설정

#10 설정: gitignore, 커밋메세지 템플릿 추가
  .github/COMMIT_EDITMSG
  web/.gitignore
Labels: ⚙ 설정

#13 [#12] 기능: 안드로이드 스플래시 페이지 추가
  android/.idea/inspectionProfiles/Project_Default.xml
  android/app/build.gradle
  android/app/src/main/java/com/example/breadmap/MainActivity.kt
  android/app/src/main/java/com/example/breadmap/Route.kt
  android/app/src/main/java/com/example/breadmap/pages/LoginPage.kt
  android/app/src/main/java/com/example/breadmap/pages/MainPage.kt
  android/app/src/main/res/raw/loading_lottie.json
Labels: 💡 기능

#18 [#15] 디자인: modern.css 추가
  web/.vscode/extensions.json
  web/.vscode/settings.json
  web/.yarn/sdks/prettier/index.js
  web/.yarn/sdks/prettier/package.json
  web/package.json
  web/src/components/home/Card.test.tsx
  web/src/components/home/Card.tsx
  web/src/components/home/Container.test.tsx
  web/src/components/home/Container.tsx
  web/src/components/home/Description.test.tsx
  web/src/components/home/Description.tsx
  web/src/components/home/Footer.tsx
  web/src/components/home/Grid.test.tsx
  web/src/components/home/Grid.tsx
  web/src/components/home/Main.test.tsx
  web/src/components/home/Main.tsx
  web/src/hooks/useGlobalTheme.tsx
  web/src/pages/_app.tsx
  web/src/pages/index.tsx
  web/src/styles/globals.ts
  web/src/styles/styled.d.ts
  web/src/styles/theme.ts
Labels: 🎨 디자인

#22 [#15] 설정: themeProvicer 설정 추가, prettier 수정
  web/.vscode/extensions.json
  web/.vscode/settings.json
  web/.yarn/sdks/prettier/index.js
  web/.yarn/sdks/prettier/package.json
  web/package.json
  web/src/components/.tmp
  web/src/components/home/Card.test.tsx
  web/src/components/home/Card.tsx
  web/src/components/home/Container.test.tsx
  web/src/components/home/Container.tsx
  web/src/components/home/Description.test.tsx
  web/src/components/home/Description.tsx
  web/src/components/home/Footer.tsx
  web/src/components/home/Grid.test.tsx
  web/src/components/home/Grid.tsx
  web/src/components/home/Main.test.tsx
  web/src/components/home/Main.tsx
  web/src/pages/_app.tsx
  web/src/pages/index.tsx
  web/src/styles/BreadMapTheming.tsx
  web/src/styles/globals.ts
  web/src/styles/styled.d.ts
  web/src/styles/theme.ts
Labels: ⚙ 설정
