Repository depromeet/bread-map-front, pull requests merged in 2022-02, with the labels that each got.

#197 설정: .env 설정을 추가합니다.
  .github/auto_assign.yml
  app/.eslintrc.js
  app/.gitignore
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/java/com/daedongbread/MainActivity.java
  app/android/settings.gradle
  app/ios/Podfile.lock
  app/ios/daedongbread.xcodeproj/project.pbxproj
  app/ios/daedongbread.xcodeproj/xcshareddata/xcschemes/daedongbreadDev.xcscheme
  app/ios/daedongbread.xcodeproj/xcshareddata/xcschemes/daedongbreadProd.xcscheme
  app/ios/daedongbread.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  app/ios/daedongbread/AppDelegate.m
  app/package.json
  app/src/components/example/example.tsx
  app/src/components/example/useExample.ts
  app/src/styles/theme.ts
  app/src/utils/bindHook/bindHook.ts
  app/yarn.lock
Labels: ⚙ 설정

#199 [#191] 빵집 상세페이지
  app/App.tsx
  app/ios/Podfile.lock
  app/src/components/bakeryDetail/Header/Header.tsx
  app/src/components/bakeryDetail/Header/index.ts
  app/src/components/bakeryDetail/HomeSection/HomeSection.tsx
  app/src/components/bakeryDetail/HomeSection/index.ts
  app/src/components/bakeryDetail/InfoSection/InfoRow.tsx
  app/src/components/bakeryDetail/InfoSection/InfoSection.tsx
  app/src/components/bakeryDetail/InfoSection/index.ts
  app/src/components/bakeryDetail/InfoSection/useInfoSection.ts
  app/src/components/bakeryDetail/MenuSection/MenuSection.tsx
  app/src/components/bakeryDetail/MenuSection/index.ts
  app/src/components/bakeryDetail/ReviewSection/ReviewSection.tsx
  app/src/components/bakeryDetail/ReviewSection/index.ts
  app/src/components/bakeryDetail/TabHeader/TabHeader.tsx
  app/src/components/bakeryDetail/TabHeader/index.ts
  app/src/components/bakeryDetail/devider.ts
  app/src/components/bakeryDetail/index.ts
  app/src/components/shared/Menus/Menu.tsx
  app/src/components/shared/Menus/Menus.tsx
  app/src/components/shared/Menus/index.ts
  app/src/components/shared/Rating/Rating.tsx
  app/src/components/shared/Rating/index.ts
  app/src/components/shared/icons/BreadCakeIcon.tsx
  app/src/components/shared/icons/ChevronDownIcon.tsx
  app/src/components/shared/icons/ClockIcon.tsx
  app/src/components/shared/icons/EarthIcon.tsx
  app/src/components/shared/icons/FileTextIcon.tsx
  app/src/components/shared/icons/InfoDeliveryIcon.tsx
  app/src/components/shared/icons/InfoParkingIcon.tsx
  app/src/components/shared/icons/InfoPetIcon.tsx
  app/src/components/shared/icons/InfoShippingIcon.tsx
  app/src/components/shared/icons/InfoWifiIcon.tsx
  app/src/components/shared/icons/MapPinIcon.tsx
  app/src/components/shared/icons/PhoneIcon.tsx
  app/src/components/shared/icons/ShareIcon.tsx
  app/src/components/shared/icons/StarGradientIcon.tsx
  app/src/components/shared/icons/StarIcon.tsx
  app/src/components/shared/icons/index.ts
  app/src/components/shared/images/bread.png
  app/src/components/shared/images/bread2.png
  app/src/components/shared/reviews/index.ts
  app/src/components/shared/reviews/review.tsx
  app/src/components/shared/reviews/reviews.tsx
  app/src/pages/BakeryDetailScreen.tsx
Labels: 🎨 디자인

#198 [#195] 기능 : api 설정 및 alias 설정 추가
  app/App.tsx
  app/babel.config.js
  app/ios/Podfile.lock
  app/ios/daedongbread.xcodeproj/xcshareddata/xcschemes/daedongbreadDev.xcscheme
  app/package.json
  app/src/apis/bakery/index.ts
  app/src/apis/bakery/types.ts
  app/src/apis/bakery/useGetBakeries.ts
  app/src/apis/fetcher.ts
  app/src/apis/index.ts
  app/src/components/Home/BakeryMarker/BakeryMarker.tsx
  app/src/components/Home/BakeryMarker/index.ts
  app/src/components/Home/BakeryMarker/useBakeryMarker.ts
  app/src/components/Home/Example/Example.tsx
  app/src/components/Home/Example/index.ts
  app/src/components/Home/Example/useExample.ts
  app/src/components/Home/MapBottomSheet/MapBottomSheet.tsx
  app/src/components/Home/MapBottomSheet/index.ts
  app/src/components/Home/MapBottomSheet/useMapBottomSheet.ts
  app/src/components/Home/index.ts
  app/src/components/bakeryDetail/Divider.ts
  app/src/components/bakeryDetail/Header/Header.tsx
  app/src/components/bakeryDetail/InfoSection/InfoSection.tsx
  app/src/components/bakeryDetail/InfoSection/useInfoSection.ts
  app/src/components/bakeryDetail/MenuSection/MenuSection.tsx
  app/src/components/bakeryDetail/ReviewSection/ReviewSection.tsx
  app/src/components/example/example.tsx
  app/src/components/example/index.ts
  app/src/components/shared/.gitkeep
  app/src/components/shared/Rating/Rating.tsx
  app/src/components/shared/Reviews/Review.tsx
  app/src/components/shared/Reviews/Reviews.tsx
  app/src/components/shared/Reviews/index.ts
  app/src/components/shared/icons/BreadCakeIcon.tsx
  app/src/components/shared/icons/index.ts
  app/src/components/shared/reviews/index.ts
  app/src/components/shared/ui-button/.gitkeep
  app/src/pages/BakeryDetailScreen.tsx
  app/src/pages/Home.tsx
  app/src/pages/index.ts
  app/src/utils/config/config.ts
  app/src/utils/config/index.ts
  app/src/utils/index.ts
  app/src/utils/resizePixel/index.ts
  app/src/utils/resizePixel/resizePixel.ts
  app/tsconfig.json
  app/yarn.lock
Labels: 💡 기능
